# Generated by Django 3.0.9 on 2021-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_auto_20210513_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lastUpdatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
